// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permits.proto

package com.yang.gateway.limiter;

public final class PermitsEntity {
  private PermitsEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PermitsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Permits)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 maxPermits = 1;</code>
     */
    long getMaxPermits();

    /**
     * <code>int64 currentPermits = 2;</code>
     */
    long getCurrentPermits();

    /**
     * <code>int64 rate = 3;</code>
     */
    long getRate();

    /**
     * <code>int64 lastMilliSecond = 4;</code>
     */
    long getLastMilliSecond();
  }
  /**
   * Protobuf type {@code Permits}
   */
  public  static final class Permits extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Permits)
      PermitsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Permits.newBuilder() to construct.
    private Permits(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Permits() {
      maxPermits_ = 0L;
      currentPermits_ = 0L;
      rate_ = 0L;
      lastMilliSecond_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Permits(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              maxPermits_ = input.readInt64();
              break;
            }
            case 16: {

              currentPermits_ = input.readInt64();
              break;
            }
            case 24: {

              rate_ = input.readInt64();
              break;
            }
            case 32: {

              lastMilliSecond_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yang.gateway.limiter.PermitsEntity.internal_static_Permits_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yang.gateway.limiter.PermitsEntity.internal_static_Permits_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yang.gateway.limiter.PermitsEntity.Permits.class, com.yang.gateway.limiter.PermitsEntity.Permits.Builder.class);
    }

    public static final int MAXPERMITS_FIELD_NUMBER = 1;
    private long maxPermits_;
    /**
     * <code>int64 maxPermits = 1;</code>
     */
    public long getMaxPermits() {
      return maxPermits_;
    }

    public static final int CURRENTPERMITS_FIELD_NUMBER = 2;
    private long currentPermits_;
    /**
     * <code>int64 currentPermits = 2;</code>
     */
    public long getCurrentPermits() {
      return currentPermits_;
    }

    public static final int RATE_FIELD_NUMBER = 3;
    private long rate_;
    /**
     * <code>int64 rate = 3;</code>
     */
    public long getRate() {
      return rate_;
    }

    public static final int LASTMILLISECOND_FIELD_NUMBER = 4;
    private long lastMilliSecond_;
    /**
     * <code>int64 lastMilliSecond = 4;</code>
     */
    public long getLastMilliSecond() {
      return lastMilliSecond_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (maxPermits_ != 0L) {
        output.writeInt64(1, maxPermits_);
      }
      if (currentPermits_ != 0L) {
        output.writeInt64(2, currentPermits_);
      }
      if (rate_ != 0L) {
        output.writeInt64(3, rate_);
      }
      if (lastMilliSecond_ != 0L) {
        output.writeInt64(4, lastMilliSecond_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (maxPermits_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, maxPermits_);
      }
      if (currentPermits_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, currentPermits_);
      }
      if (rate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rate_);
      }
      if (lastMilliSecond_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastMilliSecond_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yang.gateway.limiter.PermitsEntity.Permits)) {
        return super.equals(obj);
      }
      com.yang.gateway.limiter.PermitsEntity.Permits other = (com.yang.gateway.limiter.PermitsEntity.Permits) obj;

      boolean result = true;
      result = result && (getMaxPermits()
          == other.getMaxPermits());
      result = result && (getCurrentPermits()
          == other.getCurrentPermits());
      result = result && (getRate()
          == other.getRate());
      result = result && (getLastMilliSecond()
          == other.getLastMilliSecond());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAXPERMITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxPermits());
      hash = (37 * hash) + CURRENTPERMITS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentPermits());
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRate());
      hash = (37 * hash) + LASTMILLISECOND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastMilliSecond());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yang.gateway.limiter.PermitsEntity.Permits parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yang.gateway.limiter.PermitsEntity.Permits prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Permits}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Permits)
        com.yang.gateway.limiter.PermitsEntity.PermitsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yang.gateway.limiter.PermitsEntity.internal_static_Permits_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yang.gateway.limiter.PermitsEntity.internal_static_Permits_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yang.gateway.limiter.PermitsEntity.Permits.class, com.yang.gateway.limiter.PermitsEntity.Permits.Builder.class);
      }

      // Construct using com.yang.gateway.limiter.PermitsEntity.Permits.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        maxPermits_ = 0L;

        currentPermits_ = 0L;

        rate_ = 0L;

        lastMilliSecond_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yang.gateway.limiter.PermitsEntity.internal_static_Permits_descriptor;
      }

      @java.lang.Override
      public com.yang.gateway.limiter.PermitsEntity.Permits getDefaultInstanceForType() {
        return com.yang.gateway.limiter.PermitsEntity.Permits.getDefaultInstance();
      }

      @java.lang.Override
      public com.yang.gateway.limiter.PermitsEntity.Permits build() {
        com.yang.gateway.limiter.PermitsEntity.Permits result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yang.gateway.limiter.PermitsEntity.Permits buildPartial() {
        com.yang.gateway.limiter.PermitsEntity.Permits result = new com.yang.gateway.limiter.PermitsEntity.Permits(this);
        result.maxPermits_ = maxPermits_;
        result.currentPermits_ = currentPermits_;
        result.rate_ = rate_;
        result.lastMilliSecond_ = lastMilliSecond_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yang.gateway.limiter.PermitsEntity.Permits) {
          return mergeFrom((com.yang.gateway.limiter.PermitsEntity.Permits)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yang.gateway.limiter.PermitsEntity.Permits other) {
        if (other == com.yang.gateway.limiter.PermitsEntity.Permits.getDefaultInstance()) return this;
        if (other.getMaxPermits() != 0L) {
          setMaxPermits(other.getMaxPermits());
        }
        if (other.getCurrentPermits() != 0L) {
          setCurrentPermits(other.getCurrentPermits());
        }
        if (other.getRate() != 0L) {
          setRate(other.getRate());
        }
        if (other.getLastMilliSecond() != 0L) {
          setLastMilliSecond(other.getLastMilliSecond());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yang.gateway.limiter.PermitsEntity.Permits parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yang.gateway.limiter.PermitsEntity.Permits) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long maxPermits_ ;
      /**
       * <code>int64 maxPermits = 1;</code>
       */
      public long getMaxPermits() {
        return maxPermits_;
      }
      /**
       * <code>int64 maxPermits = 1;</code>
       */
      public Builder setMaxPermits(long value) {
        
        maxPermits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 maxPermits = 1;</code>
       */
      public Builder clearMaxPermits() {
        
        maxPermits_ = 0L;
        onChanged();
        return this;
      }

      private long currentPermits_ ;
      /**
       * <code>int64 currentPermits = 2;</code>
       */
      public long getCurrentPermits() {
        return currentPermits_;
      }
      /**
       * <code>int64 currentPermits = 2;</code>
       */
      public Builder setCurrentPermits(long value) {
        
        currentPermits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 currentPermits = 2;</code>
       */
      public Builder clearCurrentPermits() {
        
        currentPermits_ = 0L;
        onChanged();
        return this;
      }

      private long rate_ ;
      /**
       * <code>int64 rate = 3;</code>
       */
      public long getRate() {
        return rate_;
      }
      /**
       * <code>int64 rate = 3;</code>
       */
      public Builder setRate(long value) {
        
        rate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rate = 3;</code>
       */
      public Builder clearRate() {
        
        rate_ = 0L;
        onChanged();
        return this;
      }

      private long lastMilliSecond_ ;
      /**
       * <code>int64 lastMilliSecond = 4;</code>
       */
      public long getLastMilliSecond() {
        return lastMilliSecond_;
      }
      /**
       * <code>int64 lastMilliSecond = 4;</code>
       */
      public Builder setLastMilliSecond(long value) {
        
        lastMilliSecond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 lastMilliSecond = 4;</code>
       */
      public Builder clearLastMilliSecond() {
        
        lastMilliSecond_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Permits)
    }

    // @@protoc_insertion_point(class_scope:Permits)
    private static final com.yang.gateway.limiter.PermitsEntity.Permits DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yang.gateway.limiter.PermitsEntity.Permits();
    }

    public static com.yang.gateway.limiter.PermitsEntity.Permits getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Permits>
        PARSER = new com.google.protobuf.AbstractParser<Permits>() {
      @java.lang.Override
      public Permits parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Permits(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Permits> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Permits> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yang.gateway.limiter.PermitsEntity.Permits getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Permits_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Permits_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpermits.proto\"\\\n\007Permits\022\022\n\nmaxPermits" +
      "\030\001 \001(\003\022\026\n\016currentPermits\030\002 \001(\003\022\014\n\004rate\030\003" +
      " \001(\003\022\027\n\017lastMilliSecond\030\004 \001(\003B)\n\030com.yan" +
      "g.gateway.limiterB\rPermitsEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Permits_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Permits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Permits_descriptor,
        new java.lang.String[] { "MaxPermits", "CurrentPermits", "Rate", "LastMilliSecond", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
