spring:
  kafka:
    template:
      default-topic: gateway
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9092,localhost:9093 # 配置kafka集群地址
    consumer:
      auto-offset-reset: latest
      group-id: gateway
      client-id: gateway
    producer:
      retries: 3
      client-id: gateway
      batch-size: 4096
      buffer-memory: 40960
    listener:
      type: single
      client-id: mip-gateway
  cloud:
    gateway:
      datasource: mongo # 是否启用mongodb作为routes的持久化端，也可以配置成redis，相应的routes信息需要写入对应数据库
      ip-access-frequency: # 全局的GlobalIpAccessFrequency配置
        max-permits: 100
        rate: 100
      routes:
      - id: test
        uri: http://localhost:8090/hello
        predicates:
        - Path=/test
        filters:
        - name: MipRateLimiter
          args:
            limiterName: test
            permitsPerSecond: 10
            maxBurstSeconds: 20
        - name: Hystrix
          args:
            name: yangFallBack
            fallbackUri: forward:/fallback
  data:
    mongodb:
      host: localhost
      port: 27017
  redis:
    host: localhost # standalone模式 配置这里
    port: 6379 # standalone模式 配置这里
    #cluster:                                                #集群模式配置这里
    #  nodes: localhost:6379,localhost:6380,localhost:6381   #集群模式配置这里
    #  max-redirects: 3                                      #集群模式配置这里
    database: 0
    timeout: 6000
    password: 123456
    lettuce: # 使用了lettuce连接池，jedis对于集群执行lua脚本支持不完善
      pool:
        max-active: 8
        max-wait: 5000
        min-idle: 1
        max-idle: 8

logging:
  level:
    org.springframework.cloud:
      gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    mappings:
      enabled: false
    metrics:
      enabled: true

hystrix:
  metrics:
    enabled: true