spring:
  cloud:
    gateway:
      datasource: false
      routes:
      - id: service1_v1
        uri: http://localhost:8000/hello
        predicates:
        - Path=/test
        - Weight=service1, 50
        filters:
        - RequestRateLimiter=10, 20, #{@principalNameKeyResolver}
      - id: service1_v2
        uri: http://localhost:8000/demo
        predicates:
        - Path=/test
        - Weight=service1, 50
        filters:
        - RequestRateLimiter=10, 20, #{@principalNameKeyResolver}
        - name: Hystrix
          args:
            name: yangFallBack
            fallbackUri: forward:/fallback
      - id: common
        uri: http://localhost:8000/hello
        order: 9000
        predicates:
        - Path=/proxy
        filters:
        #- RequestRateLimiter=10000, 20000, #{@principalNameKeyResolver}
        - name: Hystrix
          args:
            name: yangFallBack
            fallbackUri: forward:/fallback
  data:
    mongodb:
      host: 106.12.80.244
      port: 32769
  redis:
    host: 106.12.80.244
    port: 32768
    jedis:
      pool:
        max-active: 8
        max-wait: 5000
        min-idle: 1
        max-idle: 8
    database: 0
    timeout: 6000
  datasource:
    druid:
      url: jdbc:mysql://106.12.80.244:3316/mydb
      username: root
      password: 98765432
      stat-view-servlet:
        login-password: 123456
        login-username: user
        enabled: false
      web-stat-filter:
        enabled: false

logging:
  level:
    org.springframework.cloud:
      gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    mappings:
      enabled: false
    metrics:
      enabled: true

hystrix:
  metrics:
    enabled: true