spring:
  cloud:
    gateway:
      routes:
      - id: common
        uri: http://localhost:8000/hello
        order: 9000
        predicates:
        - Path=/proxy
        filters:
        - name: Hystrix
          args:
            name: yangFallBack
            fallbackUri: forward:/fallback
      datasource: mongo
  data:
    mongodb:
      host: 106.12.80.244
      port: 32769
  redis:
    host: 106.12.80.244
    port: 32768
    jedis:
      pool:
        max-active: 8
        max-wait: 5000
        min-idle: 1
        max-idle: 8
    database: 0
    timeout: 6000
  datasource:
    druid:
      url: jdbc:mysql://106.12.80.244:3316/mydb
      username: root
      password: 98765432
      stat-view-servlet:
        login-password: 123456
        login-username: user
        enabled: false
      web-stat-filter:
        enabled: false

logging.level.org.springframework.cloud.gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    mappings:
      enabled: false