spring:
  kafka:
    template:
      default-topic: gateway
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9092,localhost:9093
    consumer:
      auto-offset-reset: latest
      group-id: gateway
      client-id: gateway
    producer:
      retries: 3
      client-id: gateway
      batch-size: 4096
      buffer-memory: 40960
    listener:
      type: single
      client-id: mip-gateway
  cloud:
    gateway:
      datasource: mongo
      ip-access-frequency:
        max-permits: 100
        rate: 100
      routes:
      - id: test
        uri: http://localhost:8090/hello
        predicates:
        - Path=/test
        filters:
        - name: MipRateLimiter
          args:
            limiterName: test
            permitsPerSecond: 10
            maxBurstSeconds: 20
        - name: Hystrix
          args:
            name: yangFallBack
            fallbackUri: forward:/fallback

#      - id: service1_v2
#        uri: http://localhost:8000/demo
#        predicates:
#        - Path=/test
#        - Weight=service1, 50
#        filters:
#        - name: RequestRateLimiter
#          args:
#        #    keyResolver: '#{@ipAddressKeyResolver}'
#            in-memory-rate-limiter:
#              replenish-rate: 10
#              burst-capacity: 20
#        - name: Hystrix
#          args:
#            name: yangFallBack
#            fallbackUri: forward:/fallback
#      - id: common
#        uri: http://localhost:8000/hello
#        order: 9000
#        predicates:
#        - Path=/proxy
#        filters:
#        #- RequestRateLimiter=10000, 20000, #{@principalNameKeyResolver}
#        - name: Hystrix
#          args:
#            name: yangFallBack
#            fallbackUri: forward:/fallback
  data:
    mongodb:
      host: localhost
      port: 27017
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 5000
        min-idle: 1
        max-idle: 8
    database: 0
    timeout: 6000
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/gateway
      username: root
      password: 123456
      stat-view-servlet:
        login-password: 123456
        login-username: user
        enabled: false
      web-stat-filter:
        enabled: false

redis:
  cluster:
    nodes: localhost:7000,localhost:7001,localhost:7002
    timeOut: 5000
    maxActive: 2000
    maxWaitMills: 1000
    maxIdle: 500
    minIdle: 5
    password: 123456

logging:
  level:
    org.springframework.cloud:
      gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    mappings:
      enabled: false
    metrics:
      enabled: true

hystrix:
  metrics:
    enabled: true