// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visitLog.proto

package com.yang.gateway.model;

public final class VisitLogEntity {
  private VisitLogEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VisitLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VisitLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *    double permitsPerSecond = 1;
     *    int32 maxBurstSeconds=2;
     * </pre>
     *
     * <code>string remoteAddress = 1;</code>
     */
    java.lang.String getRemoteAddress();
    /**
     * <pre>
     *    double permitsPerSecond = 1;
     *    int32 maxBurstSeconds=2;
     * </pre>
     *
     * <code>string remoteAddress = 1;</code>
     */
    com.google.protobuf.ByteString
        getRemoteAddressBytes();

    /**
     * <code>string method = 2;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();
  }
  /**
   * Protobuf type {@code VisitLog}
   */
  public  static final class VisitLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VisitLog)
      VisitLogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisitLog.newBuilder() to construct.
    private VisitLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisitLog() {
      remoteAddress_ = "";
      method_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VisitLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              remoteAddress_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yang.gateway.model.VisitLogEntity.internal_static_VisitLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yang.gateway.model.VisitLogEntity.internal_static_VisitLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yang.gateway.model.VisitLogEntity.VisitLog.class, com.yang.gateway.model.VisitLogEntity.VisitLog.Builder.class);
    }

    public static final int REMOTEADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object remoteAddress_;
    /**
     * <pre>
     *    double permitsPerSecond = 1;
     *    int32 maxBurstSeconds=2;
     * </pre>
     *
     * <code>string remoteAddress = 1;</code>
     */
    public java.lang.String getRemoteAddress() {
      java.lang.Object ref = remoteAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remoteAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *    double permitsPerSecond = 1;
     *    int32 maxBurstSeconds=2;
     * </pre>
     *
     * <code>string remoteAddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRemoteAddressBytes() {
      java.lang.Object ref = remoteAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remoteAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private volatile java.lang.Object method_;
    /**
     * <code>string method = 2;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRemoteAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, remoteAddress_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRemoteAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, remoteAddress_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yang.gateway.model.VisitLogEntity.VisitLog)) {
        return super.equals(obj);
      }
      com.yang.gateway.model.VisitLogEntity.VisitLog other = (com.yang.gateway.model.VisitLogEntity.VisitLog) obj;

      boolean result = true;
      result = result && getRemoteAddress()
          .equals(other.getRemoteAddress());
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REMOTEADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteAddress().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yang.gateway.model.VisitLogEntity.VisitLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yang.gateway.model.VisitLogEntity.VisitLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VisitLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VisitLog)
        com.yang.gateway.model.VisitLogEntity.VisitLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yang.gateway.model.VisitLogEntity.internal_static_VisitLog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yang.gateway.model.VisitLogEntity.internal_static_VisitLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yang.gateway.model.VisitLogEntity.VisitLog.class, com.yang.gateway.model.VisitLogEntity.VisitLog.Builder.class);
      }

      // Construct using com.yang.gateway.model.VisitLogEntity.VisitLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        remoteAddress_ = "";

        method_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yang.gateway.model.VisitLogEntity.internal_static_VisitLog_descriptor;
      }

      @java.lang.Override
      public com.yang.gateway.model.VisitLogEntity.VisitLog getDefaultInstanceForType() {
        return com.yang.gateway.model.VisitLogEntity.VisitLog.getDefaultInstance();
      }

      @java.lang.Override
      public com.yang.gateway.model.VisitLogEntity.VisitLog build() {
        com.yang.gateway.model.VisitLogEntity.VisitLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.yang.gateway.model.VisitLogEntity.VisitLog buildPartial() {
        com.yang.gateway.model.VisitLogEntity.VisitLog result = new com.yang.gateway.model.VisitLogEntity.VisitLog(this);
        result.remoteAddress_ = remoteAddress_;
        result.method_ = method_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yang.gateway.model.VisitLogEntity.VisitLog) {
          return mergeFrom((com.yang.gateway.model.VisitLogEntity.VisitLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yang.gateway.model.VisitLogEntity.VisitLog other) {
        if (other == com.yang.gateway.model.VisitLogEntity.VisitLog.getDefaultInstance()) return this;
        if (!other.getRemoteAddress().isEmpty()) {
          remoteAddress_ = other.remoteAddress_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yang.gateway.model.VisitLogEntity.VisitLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yang.gateway.model.VisitLogEntity.VisitLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object remoteAddress_ = "";
      /**
       * <pre>
       *    double permitsPerSecond = 1;
       *    int32 maxBurstSeconds=2;
       * </pre>
       *
       * <code>string remoteAddress = 1;</code>
       */
      public java.lang.String getRemoteAddress() {
        java.lang.Object ref = remoteAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remoteAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *    double permitsPerSecond = 1;
       *    int32 maxBurstSeconds=2;
       * </pre>
       *
       * <code>string remoteAddress = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRemoteAddressBytes() {
        java.lang.Object ref = remoteAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remoteAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *    double permitsPerSecond = 1;
       *    int32 maxBurstSeconds=2;
       * </pre>
       *
       * <code>string remoteAddress = 1;</code>
       */
      public Builder setRemoteAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remoteAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    double permitsPerSecond = 1;
       *    int32 maxBurstSeconds=2;
       * </pre>
       *
       * <code>string remoteAddress = 1;</code>
       */
      public Builder clearRemoteAddress() {
        
        remoteAddress_ = getDefaultInstance().getRemoteAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    double permitsPerSecond = 1;
       *    int32 maxBurstSeconds=2;
       * </pre>
       *
       * <code>string remoteAddress = 1;</code>
       */
      public Builder setRemoteAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        remoteAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object method_ = "";
      /**
       * <code>string method = 2;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VisitLog)
    }

    // @@protoc_insertion_point(class_scope:VisitLog)
    private static final com.yang.gateway.model.VisitLogEntity.VisitLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yang.gateway.model.VisitLogEntity.VisitLog();
    }

    public static com.yang.gateway.model.VisitLogEntity.VisitLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VisitLog>
        PARSER = new com.google.protobuf.AbstractParser<VisitLog>() {
      @java.lang.Override
      public VisitLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VisitLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VisitLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisitLog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.yang.gateway.model.VisitLogEntity.VisitLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VisitLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VisitLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016visitLog.proto\"1\n\010VisitLog\022\025\n\rremoteAd" +
      "dress\030\001 \001(\t\022\016\n\006method\030\002 \001(\tB(\n\026com.yang." +
      "gateway.modelB\016VisitLogEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VisitLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VisitLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VisitLog_descriptor,
        new java.lang.String[] { "RemoteAddress", "Method", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
